graph TD;
	pos:0,len:7 --> pos:31,len:4
	pos:0,len:7 --> pos:7,len:4
	pos:7,len:4 --> pos:21,len:10
	pos:7,len:4 --> pos:11,len:10
	pos:11,len:10 --> pos:52,len:2
	pos:21,len:10 --> pos:52,len:2
	pos:31,len:4 --> pos:45,len:7
	pos:31,len:4 --> pos:35,len:10
	pos:35,len:10 --> pos:52,len:2
	pos:45,len:7 --> pos:52,len:2
