graph TD;
	pos:0,len:7 --> pos:31,len:7
	pos:0,len:7 --> pos:7,len:4
	pos:7,len:4 --> pos:21,len:10
	pos:7,len:4 --> pos:11,len:10
	pos:11,len:10 --> pos:38,len:2
	pos:21,len:10 --> pos:38,len:2
	pos:31,len:7 --> pos:38,len:2
