package nz.ac.vuw.jenz.springboot;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;


// a simple sanity check test that will fail if the application context cannot start.
// generated by https://start.spring.io/
@SpringBootTest
class DemoApplicationTests {

	@Test
	void contextLoads() {
	}

	// advanced as per https://spring.io/guides/gs/testing-web
	@Autowired
	private Application controller;

	@Test
	void contextLoadsAdv() throws Exception {
		assertThat(controller).isNotNull();
	}

}
